interface ITableData {
  id: any;
  avatar: string;
  name: string;
  role: string;
  alamat: string;
  status: "selesai" | "dibatalkan" | "ditimbang" | "dijemput" | "diproses";
  date: string;
  pickupStatus:
    | "Kurir akan menjemput sampah Anda"
    | "Kurir sedang dalam perjalanan"
    | "Kurir tiba dilokasi"
    | null;
}

const tableData: ITableData[] = [
  {
    avatar: "https://randomuser.me/api/portraits/men/12.jpg",
    name: "Rois",
    role: "Penyumbang",
    alamat: "Jl. Sukajadi",
    status: "diproses",
    date: "Wed Jul 24 2019 19:17:16 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: null,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/76.jpg",
    name: "Bagas",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "dibatalkan",
    date: "Fri Nov 29 2019 10:43:17 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: null,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/79.jpg",
    name: "Hansen",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "selesai",
    date: "Fri Apr 03 2020 03:07:53 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: null,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/43.jpg",
    name: "Akhbar",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "ditimbang",
    date: "Fri Jun 21 2019 20:21:55 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: null,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/39.jpg",
    name: "Damar",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "dijemput",
    date: "Wed Aug 28 2019 15:31:43 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: "Kurir akan menjemput sampah Anda",
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/8.jpg",
    name: "Bintang",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "selesai",
    date: "Thu Jan 16 2020 09:53:33 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: null,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/34.jpg",
    name: "Ibnu",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "selesai",
    date: "Mon Oct 28 2019 14:44:31 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: null,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/80.jpg",
    name: "Tiyo",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "dijemput",
    date: "Tue Jul 23 2019 00:24:44 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: "Kurir akan menjemput sampah Anda",
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/13.jpg",
    name: "Rey",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "ditimbang",
    date: "Sat Feb 01 2020 12:57:03 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: null,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/86.jpg",
    name: "Azril",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "ditimbang",
    date: "Mon Sep 09 2019 12:03:25 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: null,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/74.jpg",
    name: "Julian Glover",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "ditimbang",
    date: "Fri May 22 2020 17:46:12 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: null,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/71.jpg",
    name: "Duncan Toy",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "ditimbang",
    date: "Sun Nov 17 2019 11:59:50 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: null,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/81.jpg",
    name: "Blanche Friesen",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "ditimbang",
    date: "Sun Jun 21 2020 16:46:39 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: null,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/91.jpg",
    name: "Orion Koepp",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "ditimbang",
    date: "Thu Jun 04 2020 18:29:41 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: null,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/49.jpg",
    name: "Dakota Vandervort",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "ditimbang",
    date: "Fri Jan 31 2020 13:02:55 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: null,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/85.jpg",
    name: "Lily Collier",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "ditimbang",
    date: "Sun Aug 18 2019 14:52:01 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: null,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/63.jpg",
    name: "Kayleigh Schumm",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "ditimbang",
    date: "Wed May 06 2020 17:49:09 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: null,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/25.jpg",
    name: "General McGlynn",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "ditimbang",
    date: "Mon Mar 30 2020 01:24:54 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: null,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/19.jpg",
    name: "Shayna Schumm",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "ditimbang",
    date: "Wed Jul 03 2019 10:01:06 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: null,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/17.jpg",
    name: "Giovanna Sanford",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "ditimbang",
    date: "Tue Oct 08 2019 17:08:43 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: null,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/12.jpg",
    name: "Emie Mante",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "ditimbang",
    date: "Wed Jul 24 2019 19:17:16 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: null,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/14.jpg",
    name: "Chance Muller",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "ditimbang",
    date: "Sun Dec 01 2019 14:04:10 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: null,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/16.jpg",
    name: "Armani Torphy",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "ditimbang",
    date: "Tue Dec 24 2019 13:28:36 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: null,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/19.jpg",
    name: "Braeden Ward",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "ditimbang",
    date: "Wed Apr 15 2020 21:40:11 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: null,
  },
  {
    avatar: "https://randomuser.me/api/portraits/men/20.jpg",
    name: "Malcolm Price",
    role: "Penyumbang",
    alamat: "Jl. Soedirman",
    status: "ditimbang",
    date: "Thu Oct 24 2019 07:09:03 GMT-0300 (Brasilia Standard Time)",
    id: undefined,
    pickupStatus: null,
  },
];

export default tableData;
export type { ITableData };
